# Generated by Django 5.0.6 on 2024-07-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=10000)),
                ('products', models.ManyToManyField(to='base.product')),
            ],
        ),
    ]
