# Generated by Django 5.0.6 on 2024-07-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shop'),
        ),
    ]
